### ISSUE TITLE
Gallery page needs a zoom function for pictures viewed through it.

### ISSUE THREAD

**Issue by d7laungani** [d7laungani/Chi-Phi-App#2]
When you click a picture you cannot zoom in or out.

**Comment by epwn** [comment]
at first glance, this seems more like a feature request. in todays age of mobile and optimized browsers, i expect viewers to be able to just fucking zoom in manually. however we can probably find a library to help out with that

**Comment by d7laungani** [comment]
Yea, it was a custom ionic gallery .Surprisingly ionic does not have their own implementation

**Comment by d7laungani** [comment]
used Photo Viewer plugin to provide zooming functionality via dank ui

**Comment by epwn** [comment]
"dank UI"
