### ISSUE TITLE
Social Media link to facebook page does not resolve to correct page

### ISSUE THREAD

**Issue by d7laungani** [d7laungani/Chi-Phi-App#3]
Goal is to link directly to the Chi Phi page on the facebook app but it either resolves to facebook home page or to some other page that is not ours even though I have the correct profile id of our facebook page.

**Comment by epwn** [comment]
This should be high priority

**Comment by d7laungani** [comment]
The same link through safari links to the correct page on the facebook app so it is not a problem with the url schema, which is the basis of the redirection.

**Comment by d7laungani** [comment]
Switched to Commonwealth link and in browser instead of through app.
